### PR TITLE
Add multi-component light switch support

### LINKED ISSUE #70: Light switch doesn't show up
I have a light switch: Inovelli Dimmer Red Series LZW31-SN. It doesn't show up in the list of accessaries. (It is in the Smartthings app).

`GET https://api.smartthings.com/v1/devices` does returned the switch in the response (see below). Briefly looking into [the code](https://github.com/iklein99/homebridge-smartthings/blob/c033cd6b36fbb9fa3163de8905e86519ca3f904f/src/platform.ts#L160),  the "main" component is a switch, it should get registered. 

---

The abridged API response:
```
{
    "components": [
        {
            "id": "LEDColorConfiguration",
            "label": "LED Bar",
            "capabilities": [
                {
                    "id": "colorControl",
                    "version": 1
                },
                {
                    "id": "actuator",
                    "version": 1
                }
            ],
            "categories": [
                {
                    "name": "Other",
                    "categoryType": "manufacturer"
                }
            ]
        },
        {
            "id": "button1",
            "label": "Up button",
            "capabilities": [
                {
                    "id": "button",
                    "version": 1
                },
                {
                    "id": "sensor",
                    "version": 1
                },
                {
                    "id": "holdableButton",
                    "version": 1
                }
            ],
            "categories": [
                {
                    "name": "Other",
                    "categoryType": "manufacturer"
                }
            ]
        },
        {
            "id": "button2",
            "label": "Down button",
            "capabilities": [
                {
                    "id": "button",
                    "version": 1
                },
                {
                    "id": "sensor",
                    "version": 1
                },
                {
                    "id": "holdableButton",
                    "version": 1
                }
            ],
            "categories": [
                {
                    "name": "Other",
                    "categoryType": "manufacturer"
                }
            ]
        },
        {
            "id": "button3",
            "label": "Configuration button",
            "capabilities": [
                {
                    "id": "button",
                    "version": 1
                },
                {
                    "id": "sensor",
                    "version": 1
                },
                {
                    "id": "holdableButton",
                    "version": 1
                }
            ],
            "categories": [
                {
                    "name": "Other",
                    "categoryType": "manufacturer"
                }
            ]
        },
        {
            "id": "main",
            "label": "Celling lights",
            "capabilities": [
                {
                    "id": "switch",
                    "version": 1
                },
                {
                    "id": "configuration",
                    "version": 1
                },
                {
                    "id": "switchLevel",
                    "version": 1
                },
                {
                    "id": "refresh",
                    "version": 1
                },
                {
                    "id": "energyMeter",
                    "version": 1
                },
                {
                    "id": "powerMeter",
                    "version": 1
                },
                {
                    "id": "button",
                    "version": 1
                },
                {
                    "id": "sensor",
                    "version": 1
                },
                {
                    "id": "actuator",
                    "version": 1
                },
                {
                    "id": "holdableButton",
                    "version": 1
                }
            ],
            "categories": [
                {
                    "name": "Switch",
                    "categoryType": "manufacturer"
                }
            ]
        }
    ],
}
```

### PR DESCRIPTION
**Pull request by kliu99**
Fix #70.

### CODE REVIEW

**Comment by iklein99** [comment]
I don't think this will work.  I think the status query will fail since it only looks at the main component.

Can you run this on that device and send me the results?
curl -H "Authorization: Bearer: <YOUR ACCESS TOKEN>" \
    https://api.smartthings.com/v1/devices/<YOUR DEVICE ID>/status

Replace those fields with the proper values and send me the results.

**Comment by kliu99** [comment]
It seems working for me in my local demo. The response is attached: https://gist.github.com/kliu99/4fec6261790bfa391d46f2f5be89af03

**Comment by kliu99** [comment]
I doesn't work in my local instance. Getting comm error: https://gist.github.com/kliu99/1ab072e3d922b7ec47b6bee2e8854ef4

**Comment by kliu99** [comment]
The problem is in the lightService.ts, you are still reading from `accessory.context.device.components[0].capabilities` instead of reading from the `main` component

**Comment by iklein99** [comment]
Give it another try.

**Comment by kliu99** [comment]
Works now. Thanks for the fix.

**Comment by kliu99** [comment]
Are you planning to bump the version so I can get the update for my prod instance?

**Comment by iklein99** [comment]
Yes, I will.  The fix will be in the next release.

**Pull request closed without merging**
